#!/bin/bash

# ---------------------------
#
# Describe purpose of context here.
#
# ---------------------------
#
# Prefix variables with MLKC_.
#
# ---------------------------

export MLKC_TEST=test
